<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="3" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-04-18T09:06:35 SAST" name="Default suite" finished-at="2025-04-18T09:06:46 SAST" duration-ms="10832">
    <groups>
    </groups>
    <test started-at="2025-04-18T09:06:35 SAST" name="Default test" finished-at="2025-04-18T09:06:46 SAST" duration-ms="10832">
      <class name="api.ClothingStore.TestCases.UserAccountTestCases">
        <test-method is-config="true" signature="setupData()[pri:0, instance:api.ClothingStore.TestCases.UserAccountTestCases@26275bef]" started-at="2025-04-18T09:06:35 SAST" name="setupData" finished-at="2025-04-18T09:06:36 SAST" duration-ms="558" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setupData -->
        <test-method signature="createUserAccount()[pri:0, instance:api.ClothingStore.TestCases.UserAccountTestCases@26275bef]" started-at="2025-04-18T09:06:36 SAST" name="createUserAccount" finished-at="2025-04-18T09:06:41 SAST" duration-ms="5157" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createUserAccount -->
        <test-method signature="readUserAccount()[pri:1, instance:api.ClothingStore.TestCases.UserAccountTestCases@26275bef]" started-at="2025-04-18T09:06:41 SAST" name="readUserAccount" finished-at="2025-04-18T09:06:43 SAST" duration-ms="1369" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- readUserAccount -->
        <test-method signature="updateUserAccount()[pri:2, instance:api.ClothingStore.TestCases.UserAccountTestCases@26275bef]" started-at="2025-04-18T09:06:43 SAST" name="updateUserAccount" finished-at="2025-04-18T09:06:44 SAST" duration-ms="1436" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- updateUserAccount -->
        <test-method signature="deleteUserAccount()[pri:3, instance:api.ClothingStore.TestCases.UserAccountTestCases@26275bef]" started-at="2025-04-18T09:06:44 SAST" name="deleteUserAccount" finished-at="2025-04-18T09:06:46 SAST" duration-ms="2238" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Expected confirmation of account deletion expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Expected confirmation of account deletion expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at api.ClothingStore.TestCases.UserAccountTestCases.deleteUserAccount(UserAccountTestCases.java:156)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- deleteUserAccount -->
      </class> <!-- api.ClothingStore.TestCases.UserAccountTestCases -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
